### ISSUE TITLE
Unfortunately it doesn't work with the function Queue Node (rgthree)

### ISSUE THREAD

**Issue by BenderBlender** [chrisgoringe/cg-use-everywhere#108]
You have a wonderful set of nodes to makes the comfyui really comfortable! But unfortunately, it does not support the function of selectively launching a separate branch of the workflow implemented in Queue Node (rgthree). I understand that you can’t do anything about this, but perhaps you could add something similar to the functionality of your nodes?

![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/116355906/6427c268-f79f-42d5-9b25-93f7334b8171)

https://github.com/rgthree/rgthree-comfy
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/116355906/bb796df7-7914-43d7-b453-8237ca257af7)

**Comment by rgthree** [comment]
This is now fixed from the [rgthree-comfy](https://github.com/rgthree/rgthree-comfy) side with https://github.com/rgthree/rgthree-comfy/commit/79f6f24a9578aa7b921322c227a63b825f2c1509

The issue was cg-use-everywhere was trying to override portions of a workflow in its override of `graphToPrompt` that no longer existed after the rgthree feature trimmed the workflow for a partial execution. Fixed on the rgthree-comfy side by moving the partial-workflow trimming to later in the process, after cg-use-everywhere already manipulates its graph (specifically, rgthree-comfy now trims the workflow in api.queuePrompt, right before sending to backend).

**Comment by chrisgoringe** [comment]
Thanks, rg3.

**Comment by BenderBlender** [comment]
Thank you very much! Everything is working!
