### ISSUE TITLE
[Bug] Show UE-Links does not work for grouped nodes

### ISSUE THREAD

**Issue by karl-von-knecht** [chrisgoringe/cg-use-everywhere#109]
I can include an "Anything Everywhere?" node in a grouped node and it continues to work.
This is very nice, I always want to group the "Anything Everywhere?" node together with its source, because that reduces clutter a lot.
Sadly the "Show UE links" does not work for the grouped node. Also the target slots of of the "Anything Everywhere?" node are no longer highlighted as AE targets.
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/123109169/b24b0c5e-b4b8-4a2e-a4b0-e6fe1e5f247d)
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/123109169/b0c3ff29-6073-467f-9058-b604a37f8ede)

**Comment by chrisgoringe** [comment]
I'm surprised that grouping the UE node works at all! It's not officially supported - I've currently said in the documentation that UE connections to and from group nodes work, but UE nodes within groups don't work.

But since it works, I'll look at making the UI consistent, since your use case is a really good one (in fact, I think I'm going to adopt it as my standard practice!)

**Comment by mijuku233** [comment]
In fact, the UE probably doesn't work properly when converted to a group node.
The reason it seems to work is that `show text` outputs the previous text when there is no new text input.
You can try modifying the text and running it again, and you should get the same result as I did, with `show text` still displaying the previous text, not the new text.
![屏幕截图 2024-02-27 100425](https://github.com/chrisgoringe/cg-use-everywhere/assets/89350747/d82c1fe8-bade-4271-b699-e38ab1a91750)

**Comment by chrisgoringe** [comment]
I believe this is now working. Please open new issue if there is still a problem
