### ISSUE TITLE
vertical spacing between input fields seems off

### ISSUE THREAD

**Issue by alexopus** [chrisgoringe/cg-use-everywhere#122]
The vertical spacing for UE nodes looks different than all the other nodes.

![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/25933468/543faf6e-e890-4bd3-8d33-783440c4363c)

Not a big deal obviously, but would be nice to have it consistent.

**Comment by chrisgoringe** [comment]
It's just the Anything Everywhere?  nodes... I've been trying to fix it! But not a priority 😀

**Comment by alexopus** [comment]
Seems to be, I have some larger workflows with hundreds of nodes and only UE stands out. Not a priority ofc :D

**Comment by JorgeR81** [comment]
I agree this should not be a priority.

But if you have time to work on this, try to fix it in a way that can also solve other related issues.

For instance, when a UE? node changes size, due to parameters being converted to input, it can introduce some minor visual artifacts.  

![ue](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/96a4aa99-d651-498e-a825-c493d4ba9345)
