### ISSUE TITLE
Edit box appears behind text box (was: Input on bypassed UE? boxes can be selected)

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-use-everywhere#139]
See https://github.com/chrisgoringe/cg-use-everywhere/issues/134#issuecomment-1996135848

**Comment by chrisgoringe** [comment]
Actually, this looks to be like the standard ComfyUI behaviour?

**Comment by JorgeR81** [comment]
About the bypassed UE? nodes, I was only talking about a visual artifact.
The transparent custom fields, from the bypassed UE? nodes, are on top of the other nodes.
Here you can see the faint / transparent fields over the text edit popup, as if the popup was transparent itself ( which is not ).

Although, in terms of functionally, it behaves like the text edit pop was on top ( as it should ).
So, in this case, bypassed nodes are the only ones usable !
I can use them even in the old ( broken ) workflows I mentioned before. 

![ae](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/a706e5cd-d970-4fe6-8bef-da4eca43d7b4)

In the old workflows, non bypassed nodes look like this.
I can still type and click to show the auto complete balloon. 
But I can only see what I'm typing, indirectly ( on the custom fields ), so it's not very usable. 

![op](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/305151b8-35d2-4223-9587-53064ec263a9)

**Comment by LukeG89** [comment]
Hi, I don't know if this could be helpful. Maybe "DOM element clipping" is the cause of those display issues?

![DOM_element_clipping](https://github.com/chrisgoringe/cg-use-everywhere/assets/161304036/eeb81441-5af5-4662-938b-a18531e8e5ad)

This is when DOM is disabled:

![when_DOM_disabled](https://github.com/chrisgoringe/cg-use-everywhere/assets/161304036/6302027c-c50f-4d8f-869d-056142731cef)


And this when enabled:

![when_DOM_enabled](https://github.com/chrisgoringe/cg-use-everywhere/assets/161304036/1e9b1165-0215-40a2-8475-4c4487950b4b)


However, it doesn't work everytime. It seams to work only every two nodes, the third one still has the issue:

https://github.com/chrisgoringe/cg-use-everywhere/assets/161304036/9d0a0cda-ae01-407b-b3d9-cd4a5b834c4f

Maybe it's just a ComfyUI display issue

**Comment by JorgeR81** [comment]
For me, enabling "DOM element clipping" does not seem work.
But I only have the main issue in the old workflows. 

I still have some of these visual artifacts in the workflows created with the latest version, as you can see. 
But they don't affect usability much, because we are not going to put nodes on to of each other. 

What's important, is that the text edit popup is in front of the custom EU? node fields, as shown here.
Without this, it is not very usable.

![test04](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/563c222e-dfa5-4b19-b7a2-0021f92ec4a8)

**Comment by chrisgoringe** [comment]
It's definitely DOM element clipping, yes. 

The popup should now always be in front of the element.

I'm a bit puzzled about the issue with old workflows - I assume if you delete the UE? node and recreate it the problem goes away?

**Comment by JorgeR81** [comment]
I also thought so, but no. 
I think the issue is also related to the regular nodes, not only the EU? nodes. 
I tried to restore an old workflow by turning it into a template. 
It did not work, but I made some interesting findings. 
It seems that loading a template made from a node workflow, also partially breaks new workflows. 

So I took an old workflow, deleted all UE? nodes, and turn the rest into a template. 
Then opened a new workflow, with working UE? nodes, and loaded the new template. 
The UE? nodes that were already there, before adding in the template, still don't have the issue, after doing this. 
But if I add new UE? nodes, they will have this issue. 
And if I disconnect the original UE? nodes, they were working, they will also have this issue.
Even If I connect them back, it won't fix them.

**Comment by chrisgoringe** [comment]
I've lost track - when you say "this issue", which issue are you talking about?

Maybe you could share a workflow that has the problem (as simple a workflow as possible!)

**Comment by JorgeR81** [comment]
I'm referring to the custom fields, being in front of the text edit popup. 
This is the most serious issue, as it affects usability. 

Other people also have this. 
https://github.com/chrisgoringe/cg-use-everywhere/issues/141

Here is an png image made from an old workflow.
Can you get the workflow for this?

![ue_test](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/331fe59d-d0b9-4810-9157-d0430c27bb7d)

**Comment by JorgeR81** [comment]
This is another one.
It's a bit less complex. 
The other was Stable Cascade img2img.

![ue_test2](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/b1c011e0-abb2-44be-ae2b-cb024c701910)

**Comment by chrisgoringe** [comment]
OK, I loaded the second image there, and the edit box consistently appears in front as it should. Can you check you've got the latest update of UE?

**Comment by JorgeR81** [comment]
It's working !

I just updated right now.
This last update seems to fix this.

**Comment by JorgeR81** [comment]
There are still some cases when this happens ( see image ).
But it does not affect usability too much, because the popup belong to other nodes.

![test](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/e61c8815-a72b-4e8d-86f2-dd2576d879d9)

When the text edit popup belongs to the UE? node, it always works ( as you can see in the image ).
This is the most important for usability.

![test2](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/ba6c51cf-830e-4b1e-92f3-60e5683e5e56)

**Comment by chrisgoringe** [comment]
OK - I'm going to spin this off as a new issue because it's less important and close this one.
