### ISSUE TITLE
The input box is covered

### ISSUE THREAD

**Issue by hiowenluke** [chrisgoringe/cg-use-everywhere#141]
<img width="683" alt="image" src="https://github.com/chrisgoringe/cg-use-everywhere/assets/19872828/84cff7f8-8a20-4183-9f38-43d8e1a69f60">

**Comment by JorgeR81** [comment]
For me, it only seems to happen with old workflows. 
If I create an workflow with the latest version, it does not happen.

**Comment by JorgeR81** [comment]
If you need to use that workflow right now, you can disable autocomplete, for the UE? nodes.

![set](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/9d193a56-57b9-4211-9e95-28237901388b)

@chrisgoringe, maybe you could release a quit update with autocomplete disabled by default, in the settings, until the issue is solved.
I can keep it enabled, for testing.

**Comment by hiowenluke** [comment]
@JorgeR81 , thank you.
