### ISSUE TITLE
Seed (rgthree) randomise gets switched to fixed

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-use-everywhere#150]
See https://github.com/chrisgoringe/cg-use-everywhere/issues/146#issuecomment-2002012226

**Comment by JorgeR81** [comment]
Just a reminder,

This issue with Seed (rgthree) only happens if nodes are grouped together ( e.g. CLIP Text Encode + UE ? ).

So it may be related to the first issue, reported by @LukeG89, in which grouping these nodes causes the normal seed to change very rapidly, if `control_before_generate` is used.

**Comment by chrisgoringe** [comment]
Believe this is now fixed
