### ISSUE TITLE
[FR] Priority Boost for the other nodes

### ISSUE THREAD

**Issue by DrJKL** [chrisgoringe/cg-use-everywhere#180]
I just hit a case where I'd want to have 2 Prompt anywhere nodes of the same type, but have one only function when the other is muted.

**Comment by JorgeR81** [comment]
That's not strictly necessary for the use cases I had, but I think it would be much more convenient. 

Usually I have a single sequence of groups that use conditioning. 
The first one is the "Main prompt" group  which uses the [ Prompts Everywhere ] node.
All the other groups, which can be muted, use 2 UE? nodes for positive negative, with increasing priority.
But, I have to write down all the following group names, in that sequence, for each stage, in addition to changing the priority level for both UE? nodes.
 
If [ Prompts everywhere ] had priority levels, I think it could be used at all stages, for this use case.

But I think [ Prompts everywhere ] currently has a baseline priority of 5 and [ UE? ] a priority of 10.
https://github.com/chrisgoringe/cg-use-everywhere/discussions/168#discussioncomment-8871343

These baseline weights would need to be changed, to allow 9 extra priority levels for each node, and to keep the same priority hierarchy for each type of node. 
e.g.
UE? -- 30 ( + 9 )
Prompts -- 20 ( + 9 )
UE -- 10 ( + 9 )
UE3 -- 0 ( + 9 )

![conditioning](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/816ff549-fa37-440a-881f-37e1eaf00a5d)

**Comment by chrisgoringe** [comment]
I think UE? and prompt everywhere could have the same base priority.

**Comment by JorgeR81** [comment]
Yes, 40 different levels is probably too over the top ...
And the [ PE ] nodes would replace [ UE? ] nodes, in this use case

**Comment by JorgeR81** [comment]
This may not be applicable to the use case I described, afterall.
Because the higher priority groups cannot be allowed to send to the previous stages in the sequence, like Prompt Everywhere would do.
Right now, I just delete the previous stages, in the group regex of the UE? nodes, ( until the last UE? in the sequence, which only has 1 more option to send ).

So I still follow the same thumb rule of UE node types: _when I increase priority, I also need to increase specificity_.

But this still may be worth doing, as it could be useful in other situations. 

---

@DrJKL, how would you use this feature exactly?

Do you just want to switch between to groups with [ Prompt Everywhere ] nodes ?

In that case you could put the 2 groups in another [ Fast Groups Muter ] node, and set [ toggleRestriction ] to "_max one_". 
This way, when you enable one group, all the others groups in the node would be muted automatically.

( I have this set for InstantID and Face ID, as an example, but I actually like to use them together ... )

![rg3](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/e28b4b85-798b-4672-a381-a1296bff0142)

**Comment by DrJKL** [comment]
I was testing a few different conditioning nodes (smZ, blenderneko's, efficiency's built-in) and wanted to use the fast groups muter with `always one`.
I also used a comfyroll switch for a minute, but it only supports 2 at a time and I didn't want to wire up the logic nodes to extend that...

**Comment by JorgeR81** [comment]
Try this workflow. 
Is this what you're trying to do?
I don't think you need to change priorities on [ Prompts Everywhere ] to do this.

I also made a version with WAS nodes, to be completely wireless !

![workflow_conditioning](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/e728e7ba-a4f1-486c-bb8c-f9910728fa51)

![workflow_conditioning_was](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/08c9d48c-42f0-491c-a34f-74f68b41d49e)

**Comment by JorgeR81** [comment]
@chrisgoringe, by the way, there is a minor issue related to the UE? autocomplete widgets: they don't show up in the workflow image, as you can see in the second workflow, with the WAS nodes.
That doesn't bother me, but you may want to open an issue for that.

**Comment by DrJKL** [comment]
Yeah, I just had a default that was outside of any of the groups that I wanted to have be the lowest priority and that's when I noticed that only the `AE?` nodes had priority boost.

I was using the Inspire KSampler, but I was also seeing if I could replicate its behavior with the Efficiency Noise Control script to see if I could use it alongside the XY Plot.

**Comment by JorgeR81** [comment]
So the use case would be basically the same workflow, but the default conditioning group would have lower priority, so it does not have to be muted. 

That could work, but I think the 9 priority levels we have for the EU? nodes may be overkill for this ... 

And once you have this set up, it's very easy to just include the default conditioning group, in the Fast Groups Muter.
Actually, I included all groups at once, just by typing the shared title string "conditioning" in the [ matchTitle ] property.
This would be easier than increasing the priority level of all [ Prompts Everywhere ] nodes, on the other groups.

![rg3a](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/a7a75c40-25c5-4d42-857f-5475242bffad)

---

@DrJKL,  About  XY plots, I haven't tried the Efficiency Nodes, but the Trung0246 nodes can do very complex plots.

The latest example workflow, with some new nodes, is not working for me, but the first one here works.

https://github.com/Trung0246/ComfyUI-0246/issues/15

**Comment by DrJKL** [comment]
That does look super powerful, but not quite as clean as 
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/448862/31cce711-51d3-47e0-b27f-bee31a52fd9a)
