### ISSUE TITLE
Using bypass on a node connected to everywhere3 breaks the connection.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [chrisgoringe/cg-use-everywhere#31]
This may be a regression of #10 
I'm using this configuration:
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/52193044/33a8d6be-12e6-42e9-97c3-12242b29607c)
When the node is bypassed in this way, the connections for model and clip are broken throughout the rest of the workflow.

**Comment by chrisgoringe** [comment]
Hmmm. Are you expecting the checkpoint model and clip to go to the AE3 node, because the Lora is bypassed? I didn't realize that bypass worked like that! I thought it effectively removed the node, didn't realize it passed the data through untouched!

But I've just done the experiment without UE nodes, and bypass does actually bypass.

So this is a bug (it's the behaviour I would have expected, but not the correct behaviour!)

**Comment by GalaxyTimeMachine** [comment]
There are two options, to either bypass (ctrl+b) or disable (ctrl+m) the nodes. The bypass option should just allow the flow to continue through the node, but without that node having any effect on the outcome, and the disable option is just the same as removing the node and any connections that would normally flow through it. The current behaviour with the AE3 node makes the bypass option act like it was disabled.

**Comment by chrisgoringe** [comment]
thanks. 

I think this is fixed in 3.1 - maybe you can update and check.

With one small exception - if you bypass the node *receiving* the output of an `Anything Everywhere?` node (using the pattern matching) the data won't flow through it - the AE? node can't match to a bypassed node. But I think that's a case easy enough to avoid.

**Comment by chrisgoringe** [comment]
Fixed in 3.1
