### ISSUE TITLE
AE node cannot be rerouted

### ISSUE THREAD

**Issue by nefudev** [chrisgoringe/cg-use-everywhere#37]
Thanks for the fix for Anything EveryWhere, I have confirmed that all three types work.
However, it seems that connection by Reoute is currently not possible. Please check.
![sample4](https://github.com/chrisgoringe/cg-use-everywhere/assets/132149510/e96de0b6-2bc7-4434-bad9-6a34e4f67791)

**Comment by chrisgoringe** [comment]
That's in the docs ("Connect anything to it (directly - not via a reroute),") and is not likely to be changed.

Reroute nodes are fickle on ComfyUI, and any attempt to work with them is prone to break. Since you can put the UE node where it needs to be, I don't see there is enough value in being able to do this for the work and risk involved.
