### ISSUE TITLE
Creating a loop (not submitting workflow) causes an uninterruptible error.

### ISSUE THREAD

**Issue by Smoky78** [chrisgoringe/cg-use-everywhere#62]
https://github.com/comfyanonymous/ComfyUI/issues/2077

**Comment by chrisgoringe** [comment]
fixed in 4.3.5

**Comment by Erwin11** [comment]
still has this bug
![04 115041](https://github.com/chrisgoringe/cg-use-everywhere/assets/6300501/05478abe-43d8-40f6-b837-e9a293d6066d)

**Comment by chrisgoringe** [comment]
Please post workflow, as this might be correct behaviour if there is a loop

**Comment by Erwin11** [comment]
@chrisgoringe
Sorry, My bad. I found out.
I had linked wrong VAE port so that efficient node shows warning ,but it didn't shows up when I was installed cg-use-everywhere plugin.  So I googled & found some answer form here.

This is wrong.json
[bug.json](https://github.com/chrisgoringe/cg-use-everywhere/files/13844024/bug.json)


Screenshot (without installed cg-use-everywhere plugin):
![bug](https://github.com/chrisgoringe/cg-use-everywhere/assets/6300501/70bc6d37-5db1-462e-849a-6bf50080b448)
The mistake is wrong linked with VAE port from efficient node.

Screenshot (with cg-use-everywhere plugin):
![wrong](https://github.com/chrisgoringe/cg-use-everywhere/assets/6300501/8404533d-8253-4396-8767-0cc7dfdbf264)
efficient node's warning is missing, just popup like this.

When I linked VAE correctly from efficient node, whether or not everywhere is installed is correct.
![ok](https://github.com/chrisgoringe/cg-use-everywhere/assets/6300501/845ec13f-e150-46ac-8a24-728e215563bf)
