### ISSUE TITLE
Disconnection when using variable regex for title regex; a bit different than last time

### ISSUE THREAD

**Issue by aegis72** [chrisgoringe/cg-use-everywhere#72]
easier to demonstrate on video
https://youtu.be/CxVthCfuVWA

wf attached

Node, WFs  attached
[aegisflow.zip](https://github.com/chrisgoringe/cg-use-everywhere/files/13629297/aegisflow.zip)
[multiloader_wiring_error2.json](https://github.com/chrisgoringe/cg-use-everywhere/files/13629299/multiloader_wiring_error2.json)
[multiloader_wiring_error.json](https://github.com/chrisgoringe/cg-use-everywhere/files/13629300/multiloader_wiring_error.json)

**Comment by chrisgoringe** [comment]
OK - I'll make this clearer in the documentation.

The regex widgets can be converted to an input *BUT* the only thing that can be plugged into this input is a simple string source - by which I mean, it has to be "directly connected to the original* source of the string - a node which is just a widget where you type a string (like the Simple String node now included) has to be *directly* connected to the regex input.

In your video you are bringing the string via another node. That won't work. Not now, not ever.

Why? Because the regex needs to be evaluated *before the workflow begins*, because that is when the graph is calculated. So the regex input isn't getting the string in the usual way, it is manually looking at the node that is plugged into it and reading the widget on that node directly.

This is a hack, but it's the only way that the functionality can be supported.

**Comment by chrisgoringe** [comment]
Updated docs

**Comment by aegis72** [comment]
Yeah, I feared that was the case; IE until it runs there's no way to tell what the result of a switch will be, f/e, and so it won't ever work. I've started removing this sort of logic as a result, and instead using muters instead and multiple send nodes (this was how I got the controlnet piece to work)
