### ISSUE TITLE
Group regex

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-use-everywhere#74]
Split off from #73 

One other thought, and this may not be possible w/in comfy, would be to add a "group regex". IE, only send commands to the nodes inside a group with title "whatever".

**Comment by chrisgoringe** [comment]
Done in 4.6

**Comment by aegis72** [comment]
Hey Chris, I think there's a bug in the update. See this image: 
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/3e91a1b3-c254-409c-958e-ada1a2c6b1e9)

Basically, it is placing the output into the group regex field. If I roll back, all works well. Once updated (I actually uninstalled and reinstalled) UE links are broken, because it's looking for the group regex called "tensorflow etc"
[SDXL_simple_workflow.json](https://github.com/chrisgoringe/cg-use-everywhere/files/13852106/SDXL_simple_workflow.json)

Regardless, I truly appreciate you implementing this, it's going to enable some cool stuff. Attaching the WF too so you can see.

**Comment by aegis72** [comment]
But weird, in that if I make a new WF, it seems to be OK (as far as where the output is placed) although the linking is failing: 
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/5c9f4312-0acc-4836-b22c-d022cb45bcc9)

**Comment by aegis72** [comment]
If I place all the nodes in one group, then execution of the first succeeds: 
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/3519f628-adfe-4eca-8af6-e0adb4c0981c)
But in two groups, all is well: 
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/b0093c3f-4b65-4ed3-bb2f-d88f17fed656)

If Group one has .* assigned as Group RegEx, then regardless of the group two having the "Two" group regex, it conflicts with G1.

It seems like by default, it is limiting based on group membership; If it isn't in a group, by default it doesn't seem to link: 
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/56fff13e-171d-48b2-9fa4-3a14aa35583d)

**Comment by aegis72** [comment]
Old version restored: 
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/8dc98c7f-ba9f-4695-814c-a14abfba62fc)

**Comment by chrisgoringe** [comment]
Thanks for the catch and the diagnosis! Latest update should fix.

**Comment by aegis72** [comment]
Thank you! Will test in a bit. One user I have (I think you know him actually) reports it as working
