### ISSUE TITLE
Anywhere Everywhere2?

### ISSUE THREAD

**Issue by caniyabanci76** [chrisgoringe/cg-use-everywhere#76]
Is there a reason why there isn't a 2-input `Everywhere2` node?

**Comment by chrisgoringe** [comment]
No...

**Comment by chrisgoringe** [comment]
To be more informative... the AE3 node was added because using the output of a Load Checkpoint node is such a common use case. There is also the `Prompt Everywhere` node which takes two inputs and is set up specifically for positive and negative text prompts or conditionings.

I could add a general AE2, but I'm wondering how often it would be used. Can you tell me why you want it?

**Comment by caniyabanci76** [comment]
Thanks for the explanation.  I was only curious.

**Comment by DrJKL** [comment]
Another option is to follow the model of Impact's Make Image Batch and automatically add a blank input when one is filled.
