### ISSUE TITLE
Make handling of group nodes more robust

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-use-everywhere#84]
At present there may be an issue if more than one node in the group has the same sort of output

**Comment by Chalice** [comment]
Heya! Thanks for that first quick fix.

Found a second issue after the update, still using the default workflow:

1) This time make an 'Anything Everywhere?' node for both, the 'model' of the 'Load Checkpoint', and an 'Anyhing Everywhere?' node from the 'Empty latent image'
2) Unplug model and latent_image from the KSampler node. Group KSampler and VAE
3) No queueing, again

The issue seems to be Group Nodes that use several 'Anything Everywhere?' inputs. They now work fine with a single Anything Everywhere? input.
![example](https://github.com/chrisgoringe/cg-use-everywhere/assets/372744/0b1fe080-986f-40c3-adfe-b779f24c6b91)

**Comment by chrisgoringe** [comment]
Or it might be that a parent could target two different nodes in the group node. I haven't got my head around how group nodes work yet...

**Comment by Chalice** [comment]
Reopening this, alas!
Do not worry about hurrying - I know you are traveling, and RL comes first.
However, I have found another (easy) case where grouping up causes the Anywhere? nodes to fail.
I have attached an image of the workflow. The highlighted nodes get turned into a group. Workflow also attached as a JSON.
The TL;DR is, of course, that ungrouped the workflow works fine, with the grouping things fail.
![AnyGroupTest](https://github.com/chrisgoringe/cg-use-everywhere/assets/372744/97cd247a-a6b4-4cca-a7aa-4d04c6add225)
[test.json](https://github.com/chrisgoringe/cg-use-everywhere/files/13853409/test.json)

**Comment by Chalice** [comment]
Adding to this, the problem reveals itself when ungrouping the nodes again.
![UnGrouped](https://github.com/chrisgoringe/cg-use-everywhere/assets/372744/0da7fc19-87bc-4ec2-83e4-f2baa526cb5b)

**Comment by chrisgoringe** [comment]
Looks like this is probably related to the inputs being renamed - I’ll look
into it!

**Comment by chrisgoringe** [comment]
Confirmed that the problem is with renaming an input. I think I've pushed a fix.

**Comment by Chalice** [comment]
I pulled the latest change. Alas, no change in the provided workflow. The behavior is, so far, the same :/

**Comment by chrisgoringe** [comment]
Try now.

Note that the group node renames the inputs, so you need to check there is a valid regex match to the group node input name...
